### PR TITLE
Microservices dockerized

### PR DESCRIPTION
**Pull request by ramazansakin**
Microservices dockerized , MySQL db converted to H2 to test easly, sonarQube issues fixed & some refactoring done :)

### CODE REVIEW

**Comment by MovingToWeb** [comment]
hey @ramazansakin, Thanks for creating a PR. 
If i merge this, the video will be broken for comparison.
Can we merge it into a different branch to keep both of them intact?

**Comment by ramazansakin** [comment]
Yes you are right @MovingToWeb ,

Then, I ll move them to another branch and reopen a PR.

**Comment by ramazansakin** [comment]
Hey @MovingToWeb ,

I can change target branch for this PR but but I can not create a branch on your repo.
Please can you create a new branch for this PR?

**Comment by MovingToWeb** [comment]
Done @ramazansakin. I have created a branch "master-docker", you can raise a PR to that

**Comment by ramazansakin** [comment]
PR edited.

**Pull request merged**
